### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by GGreenNine**
I increased the speed of your code by about 8 times, and also reduced the allocations

### CODE REVIEW

**Comment by RafaelKuebler** [comment]
Hi GGreenNine, thanks for your contribution! I just pushed into the "pull_request"-branch before merging into master. Maybe you can have a look at it and tell me your opinion.

**Comment by RafaelKuebler** [comment]
Hi GGreenNine, thanks for your contribution! I would like to merge your changes, but there are some unnecessary files that would just take away space in the repository: the comparison folder, the zip, and the .idea folder. It would be nice if you could remove those files from the commit history. If you want to preview the resulting code that I would merge you can check out the pull_request-branch.
Some notes on the changes I made/reverted:
- I would like to keep publically accessible interfaces generic (i.e. IEnumerables, ICollections, ...)
- I prefer auto-properties over public fields
- I prefer no leading underscores in private class variables
- I removed the button on the interface, as it does not serve a real purpose (other than debugging)

Thanks a lot and cheers!

**Comment by GGreenNine** [comment]
Hi. I would like to clarify that when using these interfaces, performance
suffers in some places, since Edge is now a structure and now when it
enters a method through a public interface, boxing will occur. Also,
auto-properties is not needed in case there are not used, also they create
perfomance issues, couse get and set is 2 difeerent methods, and every time
you want to get or set it, it calls a method. I agree with everything else.


пн, 2 дек. 2019 г. в 04:12, Rafael Kübler da Silva <notifications@github.com

**Comment by RafaelKuebler** [comment]
Ok, I agree. However, I see you are still making changes on the branch to be merged. Just let me know when you have finished and removed the above-mentioned files from the history and I will have a look at it again.

**Comment by RafaelKuebler** [comment]
Hi again GGreenNine,
I see you keep committing on the branch to be merged, changing big portions to Russian. Therefore, I am a little confused about the purpose of the pull request. If you intend to develop independently on your fork, that is completely fine by me. After all, the project is licensed as MIT.
Please understand that I cannot merge your master branch in the state that it is currently in into my master branch, so I am closing the pull request.
Happy coding!

**Comment by GGreenNine** [comment]
Sorry for the long answer, I was extremely busy and there was no time to
fix the request pool, I will try to do it in the near future, but I still
have a lot of work, so I can’t promise, all the best!

чт, 5 дек. 2019 г., 0:18 Rafael Kübler da Silva <notifications@github.com>:

**Pull request closed without merging**
